import {
  TwitterIcon,
  InstagramIcon,
  GitHubIcon,
  LinkedInIcon,
  TikTokIcon,
  FacebookIcon,
  DiscordIcon,
  LinktreeIcon,
  YoutubeIcon,
  TwitchIcon,
  MediumIcon,
  BehanceIcon,
  PinterestIcon,
  SoundcloudIcon,
  SpotifyIcon,
} from "@/components/SocialIcons";

export const socials = [
  { name: "twitter", icon: TwitterIcon, url: "https://twitter.com/" },
  { name: "github", icon: GitHubIcon, url: "https://github.com/" },
  { name: "TikTok", icon: TikTokIcon, url: "https://www.tiktok.com/@" },
  { name: "Facebook", icon: FacebookIcon, url: "https://www.facebook.com/" },
  { name: "LinkedIn", icon: LinkedInIcon, url: "https://www.linkedin.com/in/" },
  { name: "Discord", icon: DiscordIcon, url: "https://discord.com/users/" },
  { name: "Linktree", icon: LinktreeIcon, url: "https://linktr.ee/" },
  {
    name: "Youtube",
    icon: YoutubeIcon,
    url: "https://www.youtube.com/channel/",
  },
  { name: "Twitch", icon: TwitchIcon, url: "https://www.twitch.tv/" },
  { name: "Medium", icon: MediumIcon, url: "https://medium.com/@" },
  { name: "Behance", icon: BehanceIcon, url: "https://www.behance.net/" },
  { name: "Pinterest", icon: PinterestIcon, url: "https://www.pinterest.com/" },
  { name: "instagram", icon: InstagramIcon, url: "https://www.instagram.com/" },
  { name: "soundcloud", icon: SoundcloudIcon, url: "https://soundcloud.com/" },
  { name: "spotify", icon: SpotifyIcon, url: "https://open.spotify.com/" },
];
