import Head from "next/head";

import BasicContentLayout from "@/components/layout/Index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nodus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="#" />
      </Head>
      <main>
        <BasicContentLayout />
      </main>
    </>
  );
}
