import Head from "next/head";
import useSWRInfinite from "swr/infinite";
import { useInView } from "react-intersection-observer";
import { useState, useEffect } from "react";
import CardSm from "@/components/product/card-sm";

import Gallery from "@/components/product/gallery";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nodus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="#" />
      </Head>
      <main>
        <div>
          {/* Recommended */}

          <Gallery type="recommend"></Gallery>
          {/* videos */}
          <Gallery type="videos"></Gallery>
        </div>
      </main>
    </>
  );
}
